fix: add --repo flag to gh commands in CircleCI jobs
gh CLI needs to know which repository to work with. The orb doesn't automatically
set a default repo, so we need to specify it explicitly.

Error: No default remote repository has been set for this directory

Fix: Add '--repo dachrisch/leaguesphere' to all gh commands